name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (e.g. v1.2.3 or commit sha)'
        required: true
        default: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.IMAGE_PREFIX || 'ghcr.io/lennart-3108' }}/matchleague-backend:${{ github.event.inputs.image_tag }}
            ${{ secrets.IMAGE_PREFIX || 'ghcr.io/lennart-3108' }}/matchleague-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.IMAGE_PREFIX || 'ghcr.io/lennart-3108' }}/matchleague-frontend:${{ github.event.inputs.image_tag }}
            ${{ secrets.IMAGE_PREFIX || 'ghcr.io/lennart-3108' }}/matchleague-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig (from secret)
        # Writes the KUBECONFIG secret to a temporary file (never printed). Ensure
        # KUBECONFIG is stored as a repository secret — never commit kubeconfig to the repo.
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 600 /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig

      - name: Apply k8s manifests (create resources if absent)
        env:
          KUBECONFIG: /tmp/kubeconfig
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-hpa.yaml || true
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Update deployment images (safe, no repo edits)
        env:
          KUBECONFIG: /tmp/kubeconfig
        run: |
          IMAGE_PREFIX=${{ secrets.IMAGE_PREFIX || 'ghcr.io/lennart-3108' }}
          TAG=${{ github.event.inputs.image_tag }}
          echo "Updating backend image to ${IMAGE_PREFIX}/matchleague-backend:${TAG}"
          kubectl set image deployment/matchleague-backend backend=${IMAGE_PREFIX}/matchleague-backend:${TAG} --record
          echo "Updating frontend image to ${IMAGE_PREFIX}/matchleague-frontend:${TAG}"
          kubectl set image deployment/matchleague-frontend frontend=${IMAGE_PREFIX}/matchleague-frontend:${TAG} --record
