name: Create Deploy Pull Request

on:
  workflow_dispatch:
    inputs:
      base:
        description: Base branch
        required: true
        default: main
      title:
        description: PR title
        required: false
        default: Deploy: ready
  push:
    branches:
      - develop

jobs:
  build-and-pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install (workspaces)
        run: npm ci

      - name: Build (root)
        run: npm run build

      - name: Prepare deploy note
        run: |
          mkdir -p .github/deploy-notes
          printf "Build OK\nRun: ${GITHUB_RUN_ID}\n" > ".github/deploy-notes/${GITHUB_RUN_ID}.txt"

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.inputs.base || 'main' }}
          branch: deploy/${{ github.run_id }}
          title: ${{ github.event.inputs.title || 'Deploy: ready' }}
          commit-message: "chore: prepare deploy (#${{ github.run_id }})"
          body: |
            Automated deploy PR

            - Root build: OK

            Generated by CI (run ${{ github.run_id }}).
          labels: |
            deploy
            automated
          draft: false
