name: CI/CD — Frontend (dev)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build --if-present

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to Hostinger via lftp (FTPS)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Deploying ./frontend/build to $FTP_HOST:/public_html via FTPS"
          # try FTPS upload, disable certificate verification in case host has self-signed
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASS ftps://$FTP_HOST; mirror -R ./frontend/build /public_html --delete --verbose"
          echo "lftp exit: $?"

      - name: Smoke test
        run: |
          echo "Waiting 3s for server..."
          sleep 3
          curl -I --silent --fail https://dev.matchleague.org | sed -n '1,5p'
