name: Smoke Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    env:
      API_BASE: http://localhost:5001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend deps
        working-directory: ./backend
        run: |
          npm ci

      - name: Start backend
        working-directory: ./backend
        run: |
          # start backend in background
          npm start &
          echo $! > backend_pid.txt
        env:
          # override any env if necessary
          PORT: 5001

      - name: Wait for backend to be ready
        run: |
          # Wait up to 30s for port 5001 to be open
          for i in {1..30}; do
            if nc -z localhost 5001; then
              echo "backend ready"; exit 0;
            fi
            sleep 1
          done
          echo "backend did not start in time"; exit 1

      - name: Run smoke test
        working-directory: .
        run: |
          node backend/test/smoke-teams.js --email ${{ secrets.SMOKE_ADMIN_EMAIL }} --password ${{ secrets.SMOKE_ADMIN_PASSWORD }}

      - name: Stop backend
        if: always()
        run: |
          if [ -f backend/backend_pid.txt ]; then kill -TERM $(cat backend/backend_pid.txt) || true; fi
